apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kibana
  template:
    metadata:
      labels:
        name: kibana
    spec:
      containers:
        - name: kibana
          image: kibana:7.10.1
          ports:
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch-entrypoint.default.svc.cluster.local:9200
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-entrypoint
  namespace: default
spec:
  selector:
    name: kibana
  ports:
    - port: 5601
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: kibana-alb
# spec:
#   selector:
#     name: kibana
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 5601
#   type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana-ingress
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: kibana-entrypoint
              servicePort: 80